name: 'Notify PR Review (user replaceable)'
description: 'Notify PR review requests by sending a slack message (with custom slack usernames)'
branding:
  icon: "bell"
  color: "green"
inputs:
  token:
    description: "GitHub token"
    required: true
  slackBotToken:
    description: "slack bot token for messaging"
    required: true
  emailToSlackMap:
    description: "emailToSlackMap maps email addresses to custom Slack usernames for notifications"
    required: false
  ignoreUsers:
    description: "ignoreUsers is a comma-separated list of GitHub login usernames to be ignored"
    required: false
runs:
  using: 'node16'
  main: 'index.js'
